### PR TITLE
fix: align save/cancel buttons with input fields in MUI theme propert…

### LINKED ISSUE #2395: Model properties alignment issue in Version details in "Model details" expandable section
**Describe the bug**
The alignment of the save button and the text boxes looks off in MUI theme but looks fine in PF theme.

PF theme:
Image

MUI theme:
Image

This bug is to fix the MUI theme textbox and save button alignment and height and shouldn't affect the PF theme.

**To Reproduce**
1. Go to any version "Model details" expandable section and expand it
2. Go to "Properties" below "Labels" and "Description" and try to add a property.

**Expected behavior**
Try to align the button like the version details properties section - the cause is most probably the info alert. This change shouldn't affect the PF theme.

Image

**Additional context**

/area UI

### PR DESCRIPTION
**Pull request by HarshwardhanPatil07**
## Description

Fix #2395 
Screenshot From 2026-03-21 13-20-33

Updated the Actions Td inline style to include `alignContent: 'start'` alongside `verticalAlign: 'top'` when in MUI editing mode

## How Has This Been Tested?

**Before the fix (MUI theme):**

- The save/cancel buttons appear vertically centered in the action cell
- Because the info alert adds extra height, the buttons look misaligned with the input fields

**After the fix (MUI theme):**

- The save/cancel buttons align to the top of the action cell
- This matches the height of the input fields in the Key/Value columns

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages
- [ ] Automated tests are provided as part of the PR for major new functionalities; testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).
- [ ] **For first time contributors**: Please reach out to the [Reviewers](https://github.com/kubeflow/model-registry/blob/main/OWNERS) to ensure all tests are being run, ensuring the label `ok-to-test` has been added to the PR.

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

File: clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesTableRow.tsx [hunk 1]
```diff
@@ -204,7 +206,13 @@ const ModelPropertiesTableRow: React.FC<ModelPropertiesTableRowProps> = ({
         )}
       </Td>
       {!isArchive && (
-        <Td isActionCell width={10}>
+        <Td
+          isActionCell
+          width={10}
+          style={
+            isMUITheme && isEditing ? { verticalAlign: 'top', alignContent: 'start' } : undefined
```
Comment (manaswinidas) [inline clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesTableRow.tsx]: is `verticalAlign` necessary ? I don't see any visual changes when I remove it. let me know if I'm missing something

Comment (HarshwardhanPatil07) [reply clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesTableRow.tsx]: Thank you for noticing the precedence

**Review by manaswinidas — APPROVED** [review]
/lgtm
/approve
