### PR TITLE
Unescape catalog model names / publish catalog openapi client

### LINKED ISSUE #1554: Catalog API doesn't accept escaped model names
**Describe the bug**

The model catalog's models endpoint (`/api/model_catalog/v1alpha1/sources/{source}/models/{name}`) does not accept URL-encoded model names.

**To Reproduce**

Deploy model catalog on a cluster and forward the API port:

```
$ kubectl apply -k manifests/kustomize/options/catalog
$ kubectl port-forward svc/model-catalog-model-catalog-service 8080:8080
```

Verify that the model is returned with the unescaped name:

``` 
$ curl -s http://localhost:8080/api/model_catalog/v1alpha1/sources/sample_custom_catalog/models/mistralai/Mistral-7B-Instruct-v0.3 | jq
{
  "description": "The Mistral-7B-Instruct-v0.3 Large Language Model (LLM) is an instruct fine-tuned version of the Mistral-7B-v0.3.",
  "libraryName": "transformers",
...
```

But if the slash is escaped the model is not found:

```
curl -s http://localhost:8080/api/model_catalog/v1alpha1/sources/sample_custom_catalog/models/mistralai%2FMistral-7B-Instruct-v0.3 | jq
{
  "code": "Not Found",
  "message": "Unknown model or version"
}
```

**Expected behavior**
The model endpoint should work whether slashes are escaped in the model name or not.

**Additional context**

/cc @ederign

### PR DESCRIPTION
**Pull request by pboyd**
## Description

* Unescape model names in model catalog's model endpoints (fixes #1554)
- Publish the catalog's generated Go client as a package

## How Has This Been Tested?

See steps in #1554

## Merge criteria:

- [x] All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)
- [x] The commits have meaningful messages
- [x] Automated tests are provided as part of the PR for major new functionalities; testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

### CODE REVIEW

**Comment by ederign** [comment]
Thanks @pboyd! Super fast ;)

File: catalog/internal/server/openapi/api_model_catalog_service_service.go [hunk 1]
```diff
@@ -27,6 +28,10 @@ func (m *ModelCatalogServiceAPIService) GetAllModelArtifacts(ctx context.Context
 		return notFound("Unknown source"), nil
 	}
 
+	if newName, err := url.PathUnescape(name); err == nil {
+		name = newName
+	}
```
Comment (jonburdo) [inline catalog/internal/server/openapi/api_model_catalog_service_service.go:33]: If `err` is not nil should we return an error response instead of silently using the original value?

Comment (pboyd) [reply catalog/internal/server/openapi/api_model_catalog_service_service.go:33]: I didn't want to because the escaped name might be valid.

**Comment by Al-Pragliola** [comment]
- https://github.com/kubeflow/model-registry/pull/1555#pullrequestreview-3196639678

/lgtm

/approve
