### PR TITLE
fix: make tests work on fedora

### LINKED ISSUE #268: Command `make test` not working with Fedora 40
I followed the instructions from CONTRIBUTING.md, section [Podman], but I had to make additional steps to make it work:

- Export the additional environment variable to make testcontainers work with podman and SELinux:

```bash
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
```

- Add `Privileged: true` to https://github.com/kubeflow/model-registry/blob/main/internal/testutils/test_container_utils.go#L89-L92

I don't really like adding privileged permissions to the test container, but I couldn't find another way to make it work.

I will open a PR soon addressing this issue

### PR DESCRIPTION
**Pull request by Al-Pragliola**
fixes #268 

## Description
I set Privileged to true to test containers because SELinux prevented containers from reading metadata from the `conn_config.pb` file, which caused the container to use the in-memory database that does not persist data instead of the SQLite one, causing all tests to fail.

I also improved podman detection on systems that do not require a machine by adding a check to the `DOCKER_HOST` environment variable.

It's worth noting that I tried other ways to get it to work, both disabling Ryuk and trying to set different SELinux policies by following the [testcontainers podman guide](https://golang.testcontainers.org/system_requirements/using_podman/#fedora), but none of them worked.

## How Has This Been Tested?
I tested this on my local machine by running `make test`

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
thanks @Al-Pragliola for as well including documentation notes!

/lgtm

and planning to try it out locally asap to cross-check!
also if anyone else has chance to try it out on their system in the meantime :)

File: internal/testutils/test_container_utils.go [hunk 1]
```diff
@@ -164,5 +166,5 @@ func tryDetectPodmanRunning() bool {
 	if err != nil {
 		return false
 	}
-	return info.Host.MachineState == "Running"
+	return info.Host.MachineState == "Running" || strings.Contains(os.Getenv("DOCKER_HOST"), "podman.sock")
```
Comment (tarilabs) [inline internal/testutils/test_container_utils.go:169]: I believe worth noting that this addition leverage a podman configuration which is not "docker compatibility".

**Comment by tarilabs** [comment]
I'm hitting a `rosetta error: unhandled auxillary vector type 28` and unable to double-check this PR locally atm.

btw @lampajr you were on Fedora too, did you needed this changes? 🤔 or maybe with docker engine it was not required ?

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -84,6 +84,25 @@ export TESTCONTAINERS_RYUK_PRIVILEGED=true
...
+
+```sh
+systemctl --user start podman.socket
+```
+
+- set the environment variables
+
+```sh
+export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
+export TESTCONTAINERS_RYUK_PRIVILEGED=true
```
Comment (isinyaaa) [inline CONTRIBUTING.md:101]: Actually, I have to do the same things to get podman working with testcontainers on MacOS, but I usually export
```sh
DOCKER_HOST=unix://$(podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}')
```
I wonder if it resolves to the same thing on Linux 👀

File: internal/testutils/test_container_utils.go (hunk 1 above)
Comment (isinyaaa) [reply internal/testutils/test_container_utils.go:169]: I don't follow, this function is precisely checking if podman is being used, right?

**Review by isinyaaa — APPROVED** [review]
LGTM! but those instructions should apply to any OS in my experience.

**Comment by tarilabs** [comment]
fwiw works for me on Mac OSX back again with:

```
TESTCONTAINERS_RYUK_DISABLED=true make test-nocache
```

but not with

```
TESTCONTAINERS_RYUK_PRIVILEGED=true make test-nocache
```

but I'm also convinced is unrelated to this PR, confirming 

/lgtm

**Comment by lampajr** [comment]
> btw @lampajr you were on Fedora too, did you needed this changes? 🤔 or maybe with docker engine it was not required ?

Yeah exactly I am on Fedora and I can confirm that with docker I did not have to add this changes (at least so far, I can give it another try in a week when I'll come back)

File: CONTRIBUTING.md (hunk 2 above)
Comment (tarilabs) [inline CONTRIBUTING.md:101]: @Al-Pragliola can you kindly double-check if it's about `TESTCONTAINERS_RYUK_PRIVILEGED` or `TESTCONTAINERS_RYUK_DISABLED`, please?

see also: https://github.com/kubeflow/model-registry/pull/269#issuecomment-2312431157

Comment (Al-Pragliola) [reply CONTRIBUTING.md]: I removed the export to privileged, I may have had an unclean state when I tested the feature, it works now just with the change I made in the code and the export to DOCKER_HOST.

File: internal/testutils/test_container_utils.go (hunk 1 above)
Comment (Al-Pragliola) [reply internal/testutils/test_container_utils.go:169]: The reason for the OR is on Linux systems that do not need a machine to run containers.

File: CONTRIBUTING.md (hunk 2 above)
Comment (Al-Pragliola) [reply CONTRIBUTING.md]: btw it works with either of them set to true or false

**Review by tarilabs — APPROVED** [review]
thank you for re-checking @Al-Pragliola and for this doc and DX improvement!

/lgtm
/approve
