### PR TITLE
fix(UI): match toolbar filter input height to dropdown and button in MUI mode

### LINKED ISSUE #2383: Model registry toolbar styling issue
**Describe the bug**

Image

**To Reproduce**
1. Go to model registry page and look for this toolbar 

**Expected behavior**
The filter textbox should be the same height as the other dropdown/buttons - and this shouldn't affect the Patternfly mode

/area UI

**Additional context**

### PR DESCRIPTION
**Pull request by HarshwardhanPatil07**
## Description

Model registry toolbar styling issue

The MUI theme sets 16px block padding on the filter input and positions the fieldset border 8px above the wrapper, making the search input visually taller than the adjacent MenuToggle and Button (37px).

closes #2383 

Before:

ui-bug

After:
Screenshot From 2026-03-13 22-09-43

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages
- [ ] Automated tests are provided as part of the PR for major new functionalities; testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).
- [ ] **For first time contributors**: Please reach out to the [Reviewers](https://github.com/kubeflow/model-registry/blob/main/OWNERS) to ensure all tests are being run, ensuring the label `ok-to-test` has been added to the PR.

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Comment by manaswinidas** [comment]
Please sign your commits

**Comment by manaswinidas** [comment]
The instructions are in the link in the PR description

**Comment by HarshwardhanPatil07** [comment]
@manaswinidas Thanks for the info! I am newbie and got to know something new. TY

**Comment by HarshwardhanPatil07** [comment]
I have added the signed off in commit message please check and let me know any changes

**Comment by HarshwardhanPatil07** [comment]
@manaswinidas Thank you for reviewing the changes. 

I scoped the fix to the toolbar context only, and your changes do both:

- `FormFieldset` now has a generic `fieldsetStyle` prop instead of the hardcoded `style={!field ? { insetBlockStart: '0' } : undefined}`
- `ThemeAwareSearchInput` detects toolbar context and only passes `fieldsetStyle` there
- `ModelPropertiesTableRow` is completely unaffected

File: clients/ui/frontend/src/app/pages/modelCatalogSettings/components/SourceDetailsSection.tsx [hunk 1]
```diff
@@ -82,10 +87,12 @@ const SourceDetailsSection: React.FC<SourceDetailsSectionProps> = ({
...
-          <span>
-            {formData.sourceType === CatalogSourceType.HUGGING_FACE
-              ? SOURCE_TYPE_LABELS.HUGGING_FACE
-              : SOURCE_TYPE_LABELS.YAML}
+          <span
+            id="source-type-readonly"
+            data-testid="source-type-readonly"
+            className="pf-v6-u-display-block pf-v6-u-mt-sm"
+          >
+            {sourceTypeLabel}
```
Comment (manaswinidas) [inline clients/ui/frontend/src/app/pages/modelCatalogSettings/components/SourceDetailsSection.tsx]: did you want to include this in this PR ?

Comment (HarshwardhanPatil07) [reply clients/ui/frontend/src/app/pages/modelCatalogSettings/components/SourceDetailsSection.tsx]: Doesn't actually it. But it is just reducing the nesting and gave it an id="source-type-readonly"

(no logic changes). I can remove this changes from here at have it in the existing PR to Enhance the Readability #2392

File: clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx [hunk 2]
```diff
@@ -24,12 +24,14 @@ const ThemeAwareSearchInput: React.FC<ThemeAwareSearchInputProps> = ({
   ...rest
 }) => {
   const { isMUITheme } = useThemeContext();
+  const isToolbarFieldset = className?.split(/\s+/).includes('toolbar-fieldset-wrapper');
```
Comment (manaswinidas) [inline clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx]: Nit: `isToolbarFieldset` is unnecessary — every caller of `ThemeAwareSearchInput` already passes `className="toolbar-fieldset-wrapper"`, so this is always `true`. You can pass `fieldsetStyle={{ insetBlockStart: '0' }}` unconditionally and drop this line.

Comment (HarshwardhanPatil07) [reply clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx]: Thank you for addressing that.

**Comment by HarshwardhanPatil07** [comment]
Hello @manaswinidas can you PTAL
